import {
  boolean,
  date,
  decimal,
  index,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import { id, createdAt } from "../schemaHelpers";
import { studentsTable } from "./students";
import { menuItemsTable } from "./menu";

// ---------------------------------------------------------------------------
// AI meal suggestions (SRS-171 to SRS-173)
// Generated by calling the AI API with nutrition history as context.
// Stored so the menu page can display them without a live AI call.
// wasSelected lets the AI learn which suggestions were acted on (SRS-176).
// ---------------------------------------------------------------------------
export const aiMealSuggestionsTable = pgTable(
  "ai_meal_suggestions",
  {
    id,
    studentId: uuid("student_id")
      .notNull()
      .references(() => studentsTable.id, { onDelete: "cascade" }),
    menuItemId: uuid("menu_item_id")
      .notNull()
      .references(() => menuItemsTable.id, { onDelete: "cascade" }),
    reason: text(), // e.g. "High in fiber, which has been low this week"
    forDate: date("for_date").notNull(),
    wasSelected: boolean("was_selected").notNull().default(false),
    generatedAt: createdAt,
  },
  (t) => [index("ai_suggestions_student_date_idx").on(t.studentId, t.forDate)],
);

// ---------------------------------------------------------------------------
// Nutrition trends (SRS-174 to SRS-176) — REFRAMED from clinical predictions.
//
// ORIGINAL SRS framing: "predict potential health issues", "flag deficiencies".
// SAFER REFRAME: this table stores observed nutrition trends over a period,
// shown to parents as informational summaries — NOT medical diagnoses.
//
// The UI must display a clear disclaimer: "This is nutritional information
// only, not medical advice. Consult a healthcare professional for health
// concerns." The severity field drives visual styling only (info/notice/alert),
// never clinical language in the UI copy.
//
// What the AI actually does here: compares average weekly intake against
// nutritionTargetsTable reference values and surfaces the gap as a trend.
// e.g. "Fiber intake has averaged 40% of the recommended daily amount
// over the past 3 weeks." That's a data observation, not a health prediction.
// ---------------------------------------------------------------------------
export const trendLevelEnum = pgEnum("trend_level", [
  "on_track", // within 80–120% of target
  "low", // below 80% of target
  "high", // above 120% of target
]);

export const nutritionTrendsTable = pgTable(
  "nutrition_trends",
  {
    id,
    studentId: uuid("student_id")
      .notNull()
      .references(() => studentsTable.id, { onDelete: "cascade" }),

    // The nutrient being summarised — matches columns in menuItemsTable
    nutrient: text().notNull(), // "calories" | "protein_g" | "fiber_g" | "carbs_g" | "fat_g"

    // Observed average vs reference target over this period
    averageDaily: decimal("average_daily", {
      precision: 6,
      scale: 2,
    }).notNull(),
    targetDaily: decimal("target_daily", { precision: 6, scale: 2 }).notNull(),
    percentOfTarget: decimal("percent_of_target", {
      precision: 5,
      scale: 1,
    }).notNull(), // e.g. "67.4"

    trendLevel: trendLevelEnum("trend_level").notNull(),

    periodStart: date("period_start").notNull(),
    periodEnd: date("period_end").notNull(),

    // Informational note shown in UI — plain language, no clinical framing
    // e.g. "Fiber intake has been below the reference amount most days this period."
    displayNote: text("display_note"),

    parentViewedAt: timestamp("parent_viewed_at", { withTimezone: true }),
    generatedAt: createdAt,
  },
  (t) => [
    index("nutrition_trends_student_period_idx").on(t.studentId, t.periodEnd),
  ],
);
